import Vue from 'vue'
import VueRouter from 'vue-router'
import store from '../store/index'

Vue.use(VueRouter)

const routes_main = [
  {
    path:'/main/user-manag',
    component:()=>import('views/main/user-manag.vue'),
    children:[
      {
        path:"/main/user-manag",
        redirect:'/main/user-manag/common-user-manag'
      },
      {
        path:"/main/user-manag/common-user-manag",
        component:()=>import("views/main/user-manag/common-user-manag.vue"),
        meta:{
          sub_name:"用户管理"
        }
      }
    ]
  },
  {
    path:'/main/input-manag',
    component:()=>import('views/main/input-management.vue'),
    children:[
      {
        path:"/main/input-manag/",
        redirect:"/main/input-manag/chemical-info-list"
      },
      {
        path:'/main/input-manag/chemical-info-list',
        component:()=>import('views/main/input/chemical-info-list.vue'),
        meta:{
          sub_name:"化学药品信息列表"
        }
      },
      {
        path:'/main/input-manag/device-info-list',
        component:()=>import('views/main/input/device-info-list.vue'),
        meta:{
          sub_name:"设备信息列表"
        }
      },
      {
        path:'/main/input-manag/entering-info',
        component:()=>import('views/main/input/entering-info.vue'),
        meta:{
          sub_name:"录入入库信息"
        }
      },
      {
        path:'/main/input-manag/return-input',
        component:()=>import('views/main/input/return-input.vue'),
        meta:{
          sub_name:"设备归还"
        }
      }
    ]
  },
  {
    path:"/main/output-manag",
    component:()=>import('views/main/output-management.vue'),
    children:[
      {
        path:"/main/output-manag/",
        redirect:"/main/output-manag/chemical-info-list"
      },
      {
        path:'/main/output-manag/chemical-info-list',
        component:()=>import('views/main/output/chemical-info-list.vue'),
        meta:{
          sub_name:"化学药品"
        }
      },
      {
        path:'/main/output-manag/device-info-list',
        component:()=>import('views/main/output/device-info-list.vue'),
        meta:{
          sub_name:"设备"
        }
      }
    ]
  },
  {
    path:"/main/setting",
    component:()=>import('views/main/setting.vue'),
    children:[
      {
        path:'/main/setting/inventory-remind',
        component:()=>import("views/main/settings/inventory-remind.vue"),
        meta:{
          sub_name:"库存提醒"
        }
      },
      {
        path:'/main/setting/pre-expiration-remind',
        component:()=>import("views/main/settings/pre-expiration-remind.vue"),
        meta:{
          sub_name:"预到期提醒"
        }
      }
    ]
  },
  {
    path:"/main/data-statistics",
    component:()=>import("views/main/data-statistics.vue")
  },
  {
    path:"/main/inform-manag",
    component:()=>import("views/main/inform-manag.vue")
  },
  {
    path:'/main/resource-manag',
    component:()=>import('views/main/resource-manag.vue'),
    children:[
      {
        path:'/main/resource-manag/',
        redirect:'/main/resource-manag/chemicals'
      },
      {
        path:'/main/resource-manag/chemicals',
        component:()=>import('views/main/resource-manag/chemicals.vue'),
        meta:{
          sub_name:"化学药品管理"
        }
      },
      {
        path:'/main/resource-manag/devices',
        component:()=>import('views/main/resource-manag/devices.vue'),
        meta:{
          sub_name:"实验设备管理"
        }
      }
    ]
  }
]

const routes = [
  {
    path:'/',
    redirect:'/login-in'
  },
  {
    path:'/login-in',
    component:()=>import('views/login-in/login-in.vue')
  },
  {
    path:'/main',
    redirect:'/main/user-manag',
    component:()=>import('views/main/main.vue'),
    children:routes_main
  }
]

const router = new VueRouter({
  routes,
  mode:"hash"
})

router.beforeEach((to,from,next)=>{
  if(to.path != '/login-in' && !store.state.loginInStore.isLogined){
    console.log("请先登录!")
    next('/login-in')
  }else{
    store.state.currentSubPath = to.meta.sub_name
    next()
  }
})

export default router
