import Vue from 'vue'
import VueRouter from 'vue-router'
import store from '../store/index'

Vue.use(VueRouter)

const routes = [
  {
    path:'/user-manag',
    component:()=>import('views/user-manag.vue'),
    children:[
      {
        path:"/user-manag",
        redirectTo:'/user-manag/user-manag'
      },
      {
        path:"/user-manag/common-user-manag",
        component:()=>import("views/user-manag/common-user-manag.vue"),
        meta:{
          sub_name:"用户管理"
        }
      }
    ]
  },
  {
    path:'/input-manag',
    component:()=>import('views/input-management.vue'),
    children:[
      {
        path:"/input-manag/",
        redirectTo:"/input-manag/chemical-info-list"
      },
      {
        path:'/input-manag/chemical-info-list',
        component:()=>import('views/input/chemical-info-list.vue'),
        meta:{
          sub_name:"化学药品信息列表"
        }
      },
      {
        path:'/input-manag/device-info-list',
        component:()=>import('views/input/device-info-list.vue'),
        meta:{
          sub_name:"设备信息列表"
        }
      },
      {
        path:'/input-manag/entering-info',
        component:()=>import('views/input/entering-info.vue'),
        meta:{
          sub_name:"录入入库信息"
        }
      },
      {
        path:'/input-manag/return-input',
        component:()=>import('views/input/return-input.vue'),
        meta:{
          sub_name:"设备归还"
        }
      }
    ]
  },
  {
    path:"/output-manag",
    component:()=>import('views/output-management.vue'),
    children:[
      {
        path:"/output-manag/",
        redirectTo:"/output-manag/chemical-info-list"
      },
      {
        path:'/output-manag/chemical-info-list',
        component:()=>import('views/output/chemical-info-list.vue'),
        meta:{
          sub_name:"化学药品"
        }
      },
      {
        path:'/output-manag/device-info-list',
        component:()=>import('views/output/device-info-list.vue'),
        meta:{
          sub_name:"设备"
        }
      }
    ]
  },
  {
    path:"/setting",
    component:()=>import('views/setting.vue'),
    children:[
      {
        path:'/setting/inventory-remind',
        component:()=>import("views/settings/inventory-remind.vue"),
        meta:{
          sub_name:"库存提醒"
        }
      },
      {
        path:'/setting/pre-expiration-remind',
        component:()=>import("views/settings/pre-expiration-remind.vue"),
        meta:{
          sub_name:"预到期提醒"
        }
      }
    ]
  },
  {
    path:"/data-statistics",
    component:()=>import("views/data-statistics.vue")
  },
  {
    path:"/inform-manag",
    component:()=>import("views/inform-manag.vue")
  },
  {
    path:'/resource-manag',
    component:()=>import('views/resource-manag.vue'),
    children:[
      {
        path:'/resource-manag/',
        redirectTo:'/resource-manag/chemicals'
      },
      {
        path:'/resource-manag/chemicals',
        component:()=>import('views/resource-manag/chemicals.vue'),
        meta:{
          sub_name:"化学药品管理"
        }
      },
      {
        path:'/resource-manag/devices',
        component:()=>import('views/resource-manag/devices.vue'),
        meta:{
          sub_name:"实验设备管理"
        }
      }
    ]
  }
]

const router = new VueRouter({
  routes,
  mode:"hash"
})

router.beforeEach((to,from,next)=>{
  console.log(store.state.currentSubPath = to.meta.sub_name)
  next()
})

export default router
